jdbcUrl: jdbc:mysql://127.0.0.1:3306/beginning_mind
userName: root
password: root
author: Deolin
schema:
tables:
#  -

sourceRoot:
mapperPackage:
mapperXmlPath:
entityPackage:
repositoryPackage:

isEntityUsingAlias: false
isEntityEndWithEntity: false