projectPath: /Users/deolin/Documents/project-repo/allison1875/base/src/main/java/com/spldeolin/allison1875/base/classloader
warOrFatJarPath: /Users/deolin/Documents/project-repo/allison1875/base/src/main/java/com/spldeolin/allison1875/base/classloader
giveUpResultAddedSinceTime: '2021-01-03 12:12:54'