# com.spldeolin.allison1875.base.BaseConfig
projectPath:
warOrFatJarPath:
giveUpResultAddedSinceTime:

# com.spldeolin.allison1875.si.StatuteInspectorConfig
commonPageTypeQualifier:
publicAckJsonDirectoryPath:
lawlessCsvOutputDirectoryPath: