# com.spldeolin.allison1875.base.BaseConfig
projectPath:
warOrFatJarPath:
doNotCollectWithLoadingClass:
giveUpResultAddedSinceTime:

# com.spldeolin.allison1875.da.DocAnalyzerConfig
commonPageTypeQualifier:
docOutputDirectoryPath: